# Generated by Django 3.2 on 2022-03-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='activated?'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Subscribe?'),
        ),
    ]
