# Generated by Django 3.2 on 2022-03-12 19:28

import bboard.utilities
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20220306_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Category')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='int sort')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phoneNumber', models.CharField(default=None, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Phone Number')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('indexxx', models.CharField(default=None, max_length=15, verbose_name='Index')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=1200, verbose_name='Description')),
                ('upload', models.DateTimeField(auto_now=True, verbose_name='upload')),
                ('image', models.ImageField(blank=True, upload_to=bboard.utilities.timestapppp, verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bboard.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['created_at'],
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=bboard.utilities.timestapppp, verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.product', verbose_name='P')),
            ],
            options={
                'verbose_name': 'AddImage',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
                'ordering': ('super_category__order', 'super_category__name', 'order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.category',),
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Main Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.category',),
        ),
        migrations.AddField(
            model_name='category',
            name='super_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.supercategory', verbose_name='Main Category'),
        ),
    ]
