# Generated by Django 3.2 on 2022-03-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.TextField(default=' ', max_length=1500, verbose_name='Informations'),
        ),
    ]
