# Generated by Django 3.2 on 2022-03-19 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_about_emailforsub_mainimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderjj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Name')),
                ('phoneNumber', models.CharField(default=None, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Phone Number')),
                ('address', models.CharField(default=None, max_length=100, verbose_name='Address')),
                ('indexxx', models.CharField(default=None, max_length=15, verbose_name='Index')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('opla', models.BooleanField(default=False, verbose_name='In way')),
                ('opla2', models.BooleanField(default=False, verbose_name='Opla')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
                'ordering': ['opla2', 'opla', 'date'],
            },
        ),
    ]
